# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Mod Properties
mod_version = 1.0.0-beta.8
# mod_version = 2.0.0-alpha.5.1
version_type=beta
maven_group = ru.kelcu
archives_base_name = Minedows 98

# Mods
alinlib=2.1.0-rc.6.1
# Mods support
lambdynamiclights=4.12.2+26.2